sudo: false
language: cpp
env:
    - CXX="g++-4.8"
addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - libboost1.55-dev
            - g++-4.8
before_script:
    - mkdir build
    - cd build
    - cmake ..
script: 
    - make
    - ctest --output-on-failure 
