sudo: false
language: cpp
compiler:
        - gcc
addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - libboost1.55-dev
            - g++-4.8
before_script:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - mkdir build
    - cd build
    - cmake ..
script: 
    - make
    - ctest --output-on-failure 
notifications:
    email:
        recipients:
            - martinjrobins@gmail.com
