sudo: false

language: cpp

compiler:
    - gcc
    - clang
env:
    matrix:
        - Aboria_USE_EIGEN=on CMAKE_BUILD_TYPE=Release
        - Aboria_USE_OPENMP=on CMAKE_BUILD_TYPE=Release
        - Aboria_USE_OPENMP=on Aboria_USE_EIGEN=on CMAKE_BUILD_TYPE=Release
        - CMAKE_BUILD_TYPE=Debug Aboria_COVERAGE=on Aboria_USE_EIGEN=on Aboria_USE_OPENMP=on
    global:
        - secure: Us0XAC9as4WOpXotIR0dHd8jHt+c2M5KXGOSQmE+gX/o30GMtBE7V/YkzHvbql+t0H+OkfIaBvHxYk30KHqCYiQJJpsbjjvmCLxm/+f+Vuw0J5D6yrYRJBS+6gdflU0lF/M19S1Mjl5u3uf5kLnWli8h8Hw2ZAnzmD+2vxRYO3UHfio1ACLGE3o6tBuyt9scFg0Vrg0f37o6jBdCiWzYyReBnc2bFvZBACR9iTIPdO0hwe27Td0GaPJzxm4yq0gDu6itMGzRMk1XpV79dfA3jZj2xhZqXSam4weAawDzk8J8nb1Tjv3pajuvJVn4HZ/QQIAvq7A4D5/m/mVuV37sAZIdZd4aGt8LYz1f9F0rpFBYckN5BMOttkrHAsw6W4caCexNw2KI+M7Fkubre0EBxb1arQYpOlA5OdGCDYprckffA6JPx6PRO/Dh2bLD2Wok+HtMtLg8Yv8h1oD1FqQvB6T7WDtVnq4sf1VXi2gz6zGAOCVInjCossy5FXGGKEX4QYdCiKVaqpEsmPxfOeQ3X/mlz1z796kYgoUiRSHajsL5ZGi9q+ba5eo0KK6H22GxOq7gU+AahL+rpyiwTX54C05lbR8VhyOx9yVm9AUTr0E3nuUgPmPQypuDlLVuVjTFc0iIScAVymve7M/0n3VSoOFCtXncNWePm9E+sCglm2k=

matrix:
    include:
        - compiler: gcc
          env: CMAKE_BUILD_TYPE=Debug Travis_UPDATE_DOC=on

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - libopenmpi-dev
    - libboost1.55-dev
    - gcc-4.8
    - g++-4.8
    - clang
    - doxygen
    - valgrind

before_install:
- if [ "$Aboria_COVERAGE" == "on" ]; then pip install --user cpp-coveralls; fi
- if [ "$Aboria_USE_EIGEN" == "on" ]; then wget http://bitbucket.org/eigen/eigen/get/3.3.1.tar.gz; tar -xvf 3.3.1.tar.gz;mv eigen*/Eigen .;mv eigen*/unsupported .; fi

before_script:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-4.6" CC="clang-4.6"; fi
- uname -a
- printenv
- clang++ --version 2>&1 | grep clang
- g++ --version 2>&1 | grep g++
- gcov --version | grep gcov
- valgrind --version
- grep "#define BOOST_VERSION " /usr/include/boost/version.hpp
- doxygen --version
- ls
- cmake -DAboria_COVERAGE=$Aboria_COVERAGE -DAboria_USE_EIGEN=$Aboria_USE_EIGEN -DEIGEN3_INCLUDE_DIR=. -DAboria_USE_OPENMP=$Aboria_USE_OPENMP -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE .
- git config --global user.email "martinjrobins@gmail.com"
- git config --global user.name "Martin Robinson"
- git remote rm origin
- git remote add origin https://user:${GH_TOKEN}@github.com/user/repo.git

script:
- make
- ctest --output-on-failure

after_success:
- if [ "$Aboria_COVERAGE" == "on" ]; then coveralls -e cxxtest -i src --gcov /usr/bin/gcov-4.8 --gcov-options '\-lp'; fi
- if [ "$Travis_UPDATE_DOC" == "on" ]; then source update_doc.sh; fi

notifications:
  email:
    recipients:
    - martinjrobins@gmail.com
