language: cpp
compiler:
    - clang
    - gcc
before_install:
    - sudo add-apt-repository -y ppa:boost-latest/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -y libboost1.54-dev libvtk5-dev
before_script:
    - mkdir build
    - cd build
    - cmake ..
script: 
    - make VERBOSE=1
    - which cxxtestgen
after_script:
    - ctest
